/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as NewRouteImport } from './routes/new'
import { Route as GiveawaysIndexRouteImport } from './routes/giveaways.index'
import { Route as GiveawaysIdRouteImport } from './routes/giveaways.$id'
import { Route as GiveawaysNewRouteImport } from './routes/giveaways.new'
import { Route as WishIdRouteImport } from './routes/wish.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysIndexRoute = GiveawaysIndexRouteImport.update({
  id: '/giveaways/',
  path: '/giveaways/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysIdRoute = GiveawaysIdRouteImport.update({
  id: '/giveaways/$id',
  path: '/giveaways/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysNewRoute = GiveawaysNewRouteImport.update({
  id: '/giveaways/new',
  path: '/giveaways/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WishIdRoute = WishIdRouteImport.update({
  id: '/wish/$id',
  path: '/wish/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact': typeof ImpactRoute
  '/new': typeof NewRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
  '/giveaways/new': typeof GiveawaysNewRoute
  '/wish/$id': typeof WishIdRoute
  '/giveaways/': typeof GiveawaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact': typeof ImpactRoute
  '/new': typeof NewRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
  '/giveaways/new': typeof GiveawaysNewRoute
  '/wish/$id': typeof WishIdRoute
  '/giveaways': typeof GiveawaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact': typeof ImpactRoute
  '/new': typeof NewRoute
  '/giveaways/$id': typeof GiveawaysIdRoute
  '/giveaways/new': typeof GiveawaysNewRoute
  '/wish/$id': typeof WishIdRoute
  '/giveaways/': typeof GiveawaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/how-it-works'
    | '/impact'
    | '/new'
    | '/giveaways/$id'
    | '/giveaways/new'
    | '/wish/$id'
    | '/giveaways/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/how-it-works'
    | '/impact'
    | '/new'
    | '/giveaways/$id'
    | '/giveaways/new'
    | '/wish/$id'
    | '/giveaways'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/how-it-works'
    | '/impact'
    | '/new'
    | '/giveaways/$id'
    | '/giveaways/new'
    | '/wish/$id'
    | '/giveaways/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ImpactRoute: typeof ImpactRoute
  NewRoute: typeof NewRoute
  GiveawaysIdRoute: typeof GiveawaysIdRoute
  GiveawaysNewRoute: typeof GiveawaysNewRoute
  WishIdRoute: typeof WishIdRoute
  GiveawaysIndexRoute: typeof GiveawaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/': {
      id: '/giveaways/'
      path: '/giveaways'
      fullPath: '/giveaways/'
      preLoaderRoute: typeof GiveawaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/$id': {
      id: '/giveaways/$id'
      path: '/giveaways/$id'
      fullPath: '/giveaways/$id'
      preLoaderRoute: typeof GiveawaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/new': {
      id: '/giveaways/new'
      path: '/giveaways/new'
      fullPath: '/giveaways/new'
      preLoaderRoute: typeof GiveawaysNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wish/$id': {
      id: '/wish/$id'
      path: '/wish/$id'
      fullPath: '/wish/$id'
      preLoaderRoute: typeof WishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  HowItWorksRoute: HowItWorksRoute,
  ImpactRoute: ImpactRoute,
  NewRoute: NewRoute,
  GiveawaysIdRoute: GiveawaysIdRoute,
  GiveawaysNewRoute: GiveawaysNewRoute,
  WishIdRoute: WishIdRoute,
  GiveawaysIndexRoute: GiveawaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
